# Application Properties
spring.application.name=inventory-service
server.port=8081

# Database Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=inventory_app
spring.datasource.password=inventory1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration