spring.application.name=order-service
server.port=8080

# Database Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/orders_db
spring.datasource.username=order_app
spring.datasource.password=order1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Inventory Service URL
inventory.service.url=http://localhost:8081